# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# permissions to do edit fybrikapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubeflow
  name: create-fybrik-role
rules:
- apiGroups:
  - ""  
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikapplications/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kubeflow
  name: create-fybrik-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-fybrik-role
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: pipeline-runner
