apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fybrik-housing-price-estimate-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"get-data-endpoints": [{"key": "artifacts/$PIPELINERUN/get-data-endpoints/test_endpoint.tgz",
      "name": "get-data-endpoints-test_endpoint", "path": "/tmp/outputs/test_endpoint/data"},
      {"key": "artifacts/$PIPELINERUN/get-data-endpoints/train_endpoint.tgz", "name":
      "get-data-endpoints-train_endpoint", "path": "/tmp/outputs/train_endpoint/data"}]}'
    tekton.dev/input_artifacts: '{"visualize-table": [{"name": "get-data-endpoints-train_endpoint",
      "parent_task": "get-data-endpoints"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"get-data-endpoints": [["test_endpoint", "$(results.test-endpoint.path)"],
      ["train_endpoint", "$(workspaces.get-data-endpoints.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/train_endpoint"]],
      "visualize-table": []}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline that provides
      data policy governed access to cataloged data, analyses data, trains model,
      and writes the results and catalogs them", "inputs": [{"name": "test_dataset_id",
      "type": "String"}, {"name": "train_dataset_id", "type": "String"}, {"name":
      "run_name", "type": "String"}, {"name": "intent", "type": "String"}], "name":
      "Fybrik housing price estimate pipeline"}'
spec:
  params:
  - name: intent
    value: ''
  - name: run_name
    value: ''
  - name: test_dataset_id
    value: ''
  - name: train_dataset_id
    value: ''
  pipelineSpec:
    params:
    - name: intent
    - name: run_name
    - name: test_dataset_id
    - name: train_dataset_id
    tasks:
    - name: get-data-endpoints
      params:
      - name: intent
        value: $(params.intent)
      - name: run_name
        value: $(params.run_name)
      - name: test_dataset_id
        value: $(params.test_dataset_id)
      - name: train_dataset_id
        value: $(params.train_dataset_id)
      taskSpec:
        steps:
        - name: main
          args:
          - --train_dataset_id
          - $(inputs.params.test_dataset_id)
          - --test_dataset_id
          - $(inputs.params.train_dataset_id)
          - --run_name
          - $(inputs.params.run_name)
          - --namespace
          - kubeflow
          - --intent
          - $(inputs.params.intent)
          - --test_endpoint
          - $(results.test-endpoint.path)
          - --train_endpoint
          - $(workspaces.get-data-endpoints.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/train_endpoint
          command:
          - python3
          - get_data_endpoints.py
          image: ghcr.io/fybrik/kfp-components/get_data_endpoints:latest
          env:
          - name: ORIG_PR_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['custom.tekton.dev/originalPipelineRun']
        - image: busybox
          name: output-taskrun-name
          script: |
            #!/bin/sh
            set -exo pipefail
            echo -n "$(context.taskRun.name)" > $(results.taskrun-name.path)
        - image: busybox
          name: copy-results-artifacts
          script: |
            #!/bin/sh
            set -exo pipefail
            TOTAL_SIZE=0
            ARTIFACT_SIZE=`wc -c $(workspaces.get-data-endpoints.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/train_endpoint | awk '{print $1}'`
            TOTAL_SIZE=$( expr $TOTAL_SIZE + $ARTIFACT_SIZE)
            touch $(results.train-endpoint.path)
            if [[ $TOTAL_SIZE -lt 3072 ]]; then
              cp $(workspaces.get-data-endpoints.path)/artifacts/$ORIG_PR_NAME/$(context.taskRun.name)/train_endpoint $(results.train-endpoint.path)
            fi
          onError: continue
          env:
          - name: ORIG_PR_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['custom.tekton.dev/originalPipelineRun']
        params:
        - name: intent
        - name: run_name
        - name: test_dataset_id
        - name: train_dataset_id
        results:
        - name: test-endpoint
          type: string
          description: /tmp/outputs/test_endpoint/data
        - name: train-endpoint
          type: string
          description: /tmp/outputs/train_endpoint/data
        - name: taskrun-name
          type: string
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "get data endpoints",
              "outputs": [{"name": "test_endpoint", "type": "String"}, {"name": "train_endpoint",
              "type": "String"}], "version": "get data endpoints@sha256=6647a58630d04cd336de73e6283fa986f205e3dfff9fcec195ce59414c3f2ff1"}'
            tekton.dev/template: ''
        workspaces:
        - name: get-data-endpoints
      timeout: 525600m
      workspaces:
      - name: get-data-endpoints
        workspace: fybrik-housing-price-estimate-pipeline
    - name: visualize-table
      params:
      - name: train_dataset_id
        value: $(params.train_dataset_id)
      - name: get-data-endpoints-trname
        value: $(tasks.get-data-endpoints.results.taskrun-name)
      taskSpec:
        steps:
        - name: main
          args:
          - --train_endpoint
          - $(workspaces.visualize-table.path)/artifacts/$ORIG_PR_NAME/$(params.get-data-endpoints-trname)/train_endpoint
          - --train_dataset_id
          - $(inputs.params.train_dataset_id)
          command:
          - python3
          - visualize.py
          image: ghcr.io/fybrik/kfp-components/visualize_table:latest
          env:
          - name: ORIG_PR_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['custom.tekton.dev/originalPipelineRun']
        params:
        - name: train_dataset_id
        - name: get-data-endpoints-trname
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "visualize table",
              "outputs": [], "version": "visualize table@sha256=3c747d3932adeef32d8c48afffc517707d601147035104b0b780d9473156cece"}'
            tekton.dev/template: ''
        workspaces:
        - name: visualize-table
      timeout: 525600m
      workspaces:
      - name: visualize-table
        workspace: fybrik-housing-price-estimate-pipeline
      runAfter:
      - get-data-endpoints
    workspaces:
    - name: fybrik-housing-price-estimate-pipeline
  timeout: 525600m
  workspaces:
  - name: fybrik-housing-price-estimate-pipeline
    volumeClaimTemplate:
      spec:
        storageClassName: kfp-csi-s3
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
