apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fybrik-housing-price-estimate-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"get-data-endpoints": [{"key": "artifacts/$PIPELINERUN/get-data-endpoints/test_endpoint_path.tgz",
      "name": "get-data-endpoints-test_endpoint_path", "path": "/tmp/outputs/test_endpoint_path/data"},
      {"key": "artifacts/$PIPELINERUN/get-data-endpoints/train_endpoint_path.tgz",
      "name": "get-data-endpoints-train_endpoint_path", "path": "/tmp/outputs/train_endpoint_path/data"}],
      "visualize-table": [{"key": "artifacts/$PIPELINERUN/visualize-table/mlpipeline-ui-metadata.tgz",
      "name": "mlpipeline-ui-metadata", "path": "mlpipeline-ui-metadata.json"}]}'
    tekton.dev/input_artifacts: '{"visualize-table": [{"name": "get-data-endpoints-train_endpoint_path",
      "parent_task": "get-data-endpoints"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"get-data-endpoints": [["test_endpoint_path", "$(results.test-endpoint-path.path)"],
      ["train_endpoint_path", "$(results.train-endpoint-path.path)"]], "visualize-table":
      [["mlpipeline-ui-metadata", "mlpipeline-ui-metadata.json"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline that provides
      data policy governed access to cataloged data, analyses data, trains model,
      and writes the results and catalogs them", "inputs": [{"name": "test_dataset_id",
      "type": "String"}, {"name": "train_dataset_id", "type": "String"}, {"name":
      "run_name", "type": "String"}, {"name": "intent", "type": "String"}, {"name":
      "namespace", "type": "String"}, {"name": "train_endpoint_path", "type": "String"},
      {"name": "test_endpoint_path", "type": "String"}], "name": "Fybrik housing price
      estimate pipeline"}'
spec:
  params:
  - name: intent
    value: ''
  - name: namespace
    value: ''
  - name: run_name
    value: ''
  - name: test_dataset_id
    value: ''
  - name: test_endpoint_path
    value: ''
  - name: train_dataset_id
    value: ''
  - name: train_endpoint_path
    value: ''
  pipelineSpec:
    params:
    - name: intent
    - name: namespace
    - name: run_name
    - name: test_dataset_id
    - name: test_endpoint_path
    - name: train_dataset_id
    - name: train_endpoint_path
    tasks:
    - name: get-data-endpoints
      params:
      - name: intent
        value: $(params.intent)
      - name: namespace
        value: $(params.namespace)
      - name: run_name
        value: $(params.run_name)
      - name: test_dataset_id
        value: $(params.test_dataset_id)
      - name: train_dataset_id
        value: $(params.train_dataset_id)
      taskSpec:
        steps:
        - name: main
          args:
          - --train_dataset_id
          - $(inputs.params.test_dataset_id)
          - --test_dataset_id
          - $(inputs.params.train_dataset_id)
          - --run_name
          - $(inputs.params.run_name)
          - --namespace
          - $(inputs.params.namespace)
          - --intent
          - $(inputs.params.intent)
          - --test_endpoint_path
          - $(results.test-endpoint-path.path)
          - --train_endpoint_path
          - $(results.train-endpoint-path.path)
          command:
          - python3
          - get_data_endpoints.py
          image: ghcr.io/fybrik/kfp-components/get_data_endpoints:latest
        params:
        - name: intent
        - name: namespace
        - name: run_name
        - name: test_dataset_id
        - name: train_dataset_id
        results:
        - name: test-endpoint-path
          type: string
          description: /tmp/outputs/test_endpoint_path/data
        - name: train-endpoint-path
          type: string
          description: /tmp/outputs/train_endpoint_path/data
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "get data endpoints",
              "outputs": [{"name": "test_endpoint_path", "type": "String"}, {"name":
              "train_endpoint_path", "type": "String"}], "version": "get data endpoints@sha256=2b8dec825f2a57c6ff905a5abafbfa02362153dbd4d14b12381f66193c66c9b9"}'
            tekton.dev/template: ''
      timeout: 525600m
    - name: visualize-table
      params:
      - name: get-data-endpoints-train_endpoint_path
        value: $(tasks.get-data-endpoints.results.train-endpoint-path)
      taskSpec:
        steps:
        - name: main
          args:
          - --train_file_path
          - $(inputs.params.get-data-endpoints-train_endpoint_path)
          command:
          - python
          - visualize.py
          image: ghcr.io/fybrik/kfp-components/visualize_table:latest
        params:
        - name: get-data-endpoints-train_endpoint_path
        stepTemplate:
          volumeMounts:
          - name: mlpipeline-ui-metadata
            mountPath: mlpipeline-ui-metadata.json
        volumes:
        - name: mlpipeline-ui-metadata
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "visualize table",
              "outputs": [{"name": "MLPipeline UI metadata", "type": "UI metadata"}],
              "version": "visualize table@sha256=3076abe58ef70951c03f89cbe2dbe36d3404cdcf13d652ea55449f8277c39562"}'
            tekton.dev/template: ''
      timeout: 525600m
  timeout: 525600m
