apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: privileged-kfp
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: null
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
fsGroup:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:kubeflow:kfp-csi-s3
  - system:serviceaccount:kubeflow:csi-attacher
  - system:serviceaccount:kubeflow:csi-provisioner
volumes:
- '*'